---
# สำหรับเข้ามาทาง IP address
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-admin-ing-temp
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-prod-admin
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-admin-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domain1 }}
      secretName: admin-cert
  rules:
    - host: {{ .Values.domain1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-prod-admin
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-merchant-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domain2 }}
      secretName: merchant-cert
  rules:
    - host: {{ .Values.domain2 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-prod-merchant
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-api-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domain3 }}
      secretName: api-cert
  rules:
    - host: {{ .Values.domain3 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-prod-onix-api
                port:
                  number: 80
